name = "tranquil"
description = "A blog theme for zola, simple and clean"
license = "MIT"
homepage = "https://github.com/TeaDrinkingProgrammer/tranquil"
min_version = "0.9.0"
demo = "https://teadrinkingprogrammer.github.io/tranquil-demo/"

[author]
name = "TeaDrinkingProgrammer"
homepage = "https://github.com/TeaDrinkingProgrammer"
repo = "https://github.com/TeaDrinkingProgrammer/tranquil"

[original]
author = "isunjn"
homepage = "https://github.com/isunjn"
repo = "https://github.com/isunjn/serene"